Update docker container updates to v4 (#4)
This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| [nicolargo/glances](https://nicolargo.github.io/glances/) ([source](https://github.com/nicolargo/glances)) | major | `3.3.0.1` → `4.5.3.2` |

---

### Release Notes

<details>
<summary>nicolargo/glances (nicolargo/glances)</summary>

### [`v4.5.3.2`](https://github.com/nicolargo/glances/compare/v4.5.0.5...v4.5.3.2)

[Compare Source](https://github.com/nicolargo/glances/compare/v4.5.0.5...v4.5.3.2)

### [`v4.5.0.5`](https://github.com/nicolargo/glances/compare/v4.5.0.4...v4.5.0.5)

[Compare Source](https://github.com/nicolargo/glances/compare/v4.5.0.4...v4.5.0.5)

### [`v4.5.0.4`](https://github.com/nicolargo/glances/compare/v4.5.0.2...v4.5.0.4)

[Compare Source](https://github.com/nicolargo/glances/compare/v4.5.0.2...v4.5.0.4)

### [`v4.5.0.2`](https://github.com/nicolargo/glances/compare/v4.5.0.1...v4.5.0.2)

[Compare Source](https://github.com/nicolargo/glances/compare/v4.5.0.1...v4.5.0.2)

### [`v4.5.0.1`](https://github.com/nicolargo/glances/compare/v4.3.0.8...v4.5.0.1)

[Compare Source](https://github.com/nicolargo/glances/compare/v4.3.0.8...v4.5.0.1)

### [`v4.3.0.8`](https://github.com/nicolargo/glances/releases/tag/v4.3.0.8): Glances 4.3.0.8

[Compare Source](https://github.com/nicolargo/glances/compare/v4.3.0.7...v4.3.0.8)

**Full Changelog**: <https://github.com/nicolargo/glances/compare/v4.3.0.7...v4.3.0.8>

### [`v4.3.0.7`](https://github.com/nicolargo/glances/releases/tag/v4.3.0.7): Glances 4.3.0.7

[Compare Source](https://github.com/nicolargo/glances/compare/v4.3.0.6...v4.3.0.7)

**Full Changelog**: <https://github.com/nicolargo/glances/compare/v4.3.0.6...v4.3.0.7>

### [`v4.3.0.6`](https://github.com/nicolargo/glances/releases/tag/v4.3.0.6): Glances 4.3.0.6

[Compare Source](https://github.com/nicolargo/glances/compare/v4.3.0.5...v4.3.0.6)

**Full Changelog**: <https://github.com/nicolargo/glances/compare/v4.3.0...v4.3.0.6>

##### Deprecation warning

**netifaces** is deprecated and should be uninstall. instead **netifaces2** should be install:

```
pip uninstall netifaces
pip install netifaces2
```

### [`v4.3.0.5`](https://github.com/nicolargo/glances/compare/v4.3.0.4...v4.3.0.5)

[Compare Source](https://github.com/nicolargo/glances/compare/v4.3.0.4...v4.3.0.5)

### [`v4.3.0.4`](https://github.com/nicolargo/glances/compare/v4.3.0.3...v4.3.0.4)

[Compare Source](https://github.com/nicolargo/glances/compare/v4.3.0.3...v4.3.0.4)

### [`v4.3.0.3`](https://github.com/nicolargo/glances/compare/v4.3.0.2...v4.3.0.3)

[Compare Source](https://github.com/nicolargo/glances/compare/v4.3.0.2...v4.3.0.3)

### [`v4.3.0.2`](https://github.com/nicolargo/glances/compare/v4.3.0.1...v4.3.0.2)

[Compare Source](https://github.com/nicolargo/glances/compare/v4.3.0.1...v4.3.0.2)

### [`v4.3.0.1`](https://github.com/nicolargo/glances/compare/v4.1.2.1...v4.3.0.1)

[Compare Source](https://github.com/nicolargo/glances/compare/v4.1.2.1...v4.3.0.1)

### [`v4.1.2.1`](https://github.com/nicolargo/glances/releases/tag/v4.1.2.1): Glances 4.1.2

[Compare Source](https://github.com/nicolargo/glances/compare/v3.4.0.5...v4.1.2.1)

### Version 4.1.2

Bug corrected:

- AttributeError: 'CpuPercent' object has no attribute 'cpu\_percent' [#&#8203;2859](https://github.com/nicolargo/glances/issues/2859)

### Version 4.1.1

Bug corrected:

- Sensors data is not exported using InfluxDB2 exporter [#&#8203;2856](https://github.com/nicolargo/glances/issues/2856)

### Version 4.1.0

Enhancements:

- Call process\_iter.clear\_cache() (PsUtil 6+) when Glances user force a refresh (F5 or CTRL-R) [#&#8203;2753](https://github.com/nicolargo/glances/issues/2753)
- PsUtil 6+ no longer check PID reused [#&#8203;2755](https://github.com/nicolargo/glances/issues/2755)
- Add support for automatically hiding network interfaces that are down or that don't have any IP addresses [#&#8203;2799](https://github.com/nicolargo/glances/issues/2799)

Bug corrected:

- API: Network module is disabled but appears in endpoint "all" [#&#8203;2815](https://github.com/nicolargo/glances/issues/2815)
- API is not compatible with requests containing spcial/encoding char [#&#8203;2820](https://github.com/nicolargo/glances/issues/2820)
- 'j' hot key crashs Glances [#&#8203;2831](https://github.com/nicolargo/glances/issues/2831)
- Raspberry PI - CPU info is not correct [#&#8203;2616](https://github.com/nicolargo/glances/issues/2616)
- Graph export is broken if there is no graph section in Glances configuration file [#&#8203;2839](https://github.com/nicolargo/glances/issues/2839)
- Glances API status check returns Error 405 - Method Not Allowed [#&#8203;2841](https://github.com/nicolargo/glances/issues/2841)
- Rootless podman containers cause glances to fail with KeyError [#&#8203;2827](https://github.com/nicolargo/glances/issues/2827)
- \--export-process-filter Filter using complete command [#&#8203;2824](https://github.com/nicolargo/glances/issues/2824)
- Exception when Glances is ran with limited plugin list [#&#8203;2822](https://github.com/nicolargo/glances/issues/2822)
- Disable separator option do not work [#&#8203;2823](https://github.com/nicolargo/glances/issues/2823)

Continious integration and documentation:

- test test\_107\_fs\_plugin\_method fails on aarch64-linux [#&#8203;2819](https://github.com/nicolargo/glances/issues/2819)

Thanks to all contibutors and bug reporters !

Special thanks to:

- Bharath Vignesh J K
- RazCrimson
- Vadim Smal

### [`v3.4.0.5`](https://github.com/nicolargo/glances/releases/tag/v3.4.0.5)

[Compare Source](https://github.com/nicolargo/glances/compare/v3.4.0.4...v3.4.0.5)

# Version 3.4.0.5

Correct issur with GPU plugin in Docker images [#&#8203;2705](https://github.com/nicolargo/glances/issues/2705)

# Version 3.4.0.4

Cyber security patch (update some deps in the WebUI and Docker image)

# Version 3.4.0.3

Bugs corrected:

```
* Add glances binary to '/usr/local/bin' + Update ENV PATH to include '/venv/bin' in Dockerfiles #&#8203;2419
* No more threshold display in the WebUI cpu/mem and memswap plugins #&#8203;2420
```

# Version 3.4.0.2

Bugs corrected:

```
* Cannot start Glances 3.4.0.1 on Windows 10: SIGHUP not defined #&#8203;2408
* Influxdb2 export not working #&#8203;2407
```

# Version 3.4.0.1

Bug corrected:

```
* 3.4.0 crash on startupwith minimal deps #&#8203;2401
```

# Version 3.4.0

Enhancements:

```
* Enhance process "extended stats" display (in Curses interface) #&#8203;2225
  _You can now *pin* a specific process to the top of the process list_
* Improve Glances start time by disabling Docker and Podman version getter - Related to #&#8203;1985
* Customizable InfluxDB2 export interval #&#8203;2348
* Improve kill signal management #&#8203;2194
* Display a critical error message if Glances is ran with both webserver and rpcserver mode
* Refactor the Cloud plugin, disable it by default in the default configuration file - Related to #&#8203;2279
* Correct clear-text logging of sensitive information (security alert #&#8203;29)
* Use of a broken or weak cryptographic hashing algorithm (SHA256) on password storage #&#8203;2175
```

Bug corrected:

```
* Correct issue (error message) concerning the Cloud plugin - Related to #&#8203;2392
* InfluxDB2 export doesn't process folders correctly - missing key #&#8203;2327
* Index error when displaying programs on MacOS #&#8203;2360
* Dissociate 2 sensors with exactly the same names #&#8203;2280
* All times displayed in UTC - Container not using TZ/localtime (Docker) #&#8203;2278
* It is not possible to return API data for a particular mount point (FS plugin) #&#8203;1162
```

Documentation and CI:

```
* chg: Dockerfile - structured & cleaner build process #&#8203;2386
* Ubuntu is back as additional Docker images. Alpine stays the default one. Related to #&#8203;2185
* Improve Makefile amd docker-compose to support Podman and GPU
* Workaround to pin urlib3<2.0 - Related to #&#8203;2392
* Error while generating the documentation (ModuleNotFoundError: No module named 'glances') #&#8203;2391
* Update Flamegraph (memory profiling)
* Improve template for issue report and feature request
* Parameters in the VIRT column #&#8203;2343
* Graph generation documentation is not clear #&#8203;2336
* docs: Docker - include tag details
* Add global architecture diagram (Excalidraw)
* Links to documents in sample glances.conf are not valid. #&#8203;2271
* Add semgrep support
* Smartmontools missing from full docker image #&#8203;2262
* Improve documentation regarding regexp in configuration file
* Improve documentation about the [ip] plugin #&#8203;2251
```

Cyber security update:

```
* All libs have been updated to the latest version
  Full roadmap here: https://github.com/nicolargo/glances/milestone/62?closed=1
```

Refactor the Docker images factory, from now, Alpine and Ubuntu images will be provided (nicolargo/glances):

- *latest-full* for a full Alpine Glances image (latest release) with all dependencies
- *latest* for a basic Alpine Glances (latest release) version with minimal dependencies (Bottle and Docker)
- *dev* for a basic Alpine Glances image (based on development branch) with all dependencies (Warning: may be instable)
- *ubuntu-latest-full* for a full Ubuntu Glances image (latest release) with all dependencies
- *ubuntu-latest* for a basic Ubuntu Glances (latest release) version with minimal dependencies (Bottle and Docker)
- *ubuntu-dev* for a basic Ubuntu Glances image (based on development branch) with all dependencies (Warning: may be instable)

Contributors for this version:

```
* Nicolargo
* RazCrimson: a very special thanks to @&#8203;RazCrimson for his huge work on this version !
* Bharath Vignesh J K
* Raz Crimson
* fr4nc0is
* Florian Calvet
* Ali Erdinç Köroğlu
* Jose Vicente Nunez
* Rui Chen
* Ryan Horiguchi
* mfridge
* snyk-bot
```

### [`v3.4.0.4`](https://github.com/nicolargo/glances/compare/v3.4.0.3...v3.4.0.4)

[Compare Source](https://github.com/nicolargo/glances/compare/v3.4.0.3...v3.4.0.4)

### [`v3.4.0.3`](https://github.com/nicolargo/glances/compare/v3.4.0.2...v3.4.0.3)

[Compare Source](https://github.com/nicolargo/glances/compare/v3.4.0.2...v3.4.0.3)

### [`v3.4.0.2`](https://github.com/nicolargo/glances/releases/tag/v3.4.0.2): Glances 3.4.0.2

[Compare Source](https://github.com/nicolargo/glances/compare/v3.4.0.1...v3.4.0.2)

Hotfix for [Glances 3.4.0](https://github.com/nicolargo/glances/releases/tag/v3.4.0):

- Cannot start Glances 3.4.0.1 on Windows 10: SIGHUP not defined [#&#8203;2408](https://github.com/nicolargo/glances/issues/2408)
- Influxdb2 export not working [#&#8203;2407](https://github.com/nicolargo/glances/issues/2407)

### [`v3.4.0.1`](https://github.com/nicolargo/glances/releases/tag/v3.4.0.1): Glances 3.4.0.1

[Compare Source](https://github.com/nicolargo/glances/compare/v3.3.1.1...v3.4.0.1)

Hotfix for [Glances 3.4.0](https://github.com/nicolargo/glances/releases/tag/v3.4.0):

- 3.4.0 crash on startupwith minimal deps [#&#8203;2401](https://github.com/nicolargo/glances/issues/2401)

### [`v3.3.1.1`](https://github.com/nicolargo/glances/compare/v3.3.0.4...v3.3.1.1)

[Compare Source](https://github.com/nicolargo/glances/compare/v3.3.0.4...v3.3.1.1)

### [`v3.3.0.4`](https://github.com/nicolargo/glances/compare/v3.3.0.2...v3.3.0.4)

[Compare Source](https://github.com/nicolargo/glances/compare/v3.3.0.2...v3.3.0.4)

### [`v3.3.0.2`](https://github.com/nicolargo/glances/compare/v3.3.0.1...v3.3.0.2)

[Compare Source](https://github.com/nicolargo/glances/compare/v3.3.0.1...v3.3.0.2)

</details>

---

### Configuration

📅 **Schedule**: (in timezone UTC)

- Branch creation
  - "after 5am"
- Automerge
  - At any time (no schedule defined)

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [x] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://github.com/renovatebot/renovate).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0My4yMjAuMCIsInVwZGF0ZWRJblZlciI6IjQzLjIyMC4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Reviewed-on: https://forgejo.louhome.xyz/lou-home/homelab/pulls/4
Co-authored-by: automation-svc-acct <automation@louhome.xyz>
Co-committed-by: automation-svc-acct <automation@louhome.xyz>